services:
  - type: web
    name: websistemnurse-backend
    runtime: node
    rootDir: websistemnurse-backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
